runtime: nodejs20

instance_class: F1

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:Paperboat%40123@db.fxiwmsifjsjssonfgjlv.supabase.co:5432/postgres"
  JWT_SECRET: "your-secret-key-change-this-to-something-random"
  FRONTEND_URL: "https://analyst-2-0.vercel.app"

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

handlers:
  - url: /.*
    script: auto
    secure: always
